config/routes.rb
Dynboxes::Application.routes.draw do
  get 'welcome/index'

  get '/', to: redirect('/welcome/index')

  get 'welcome/update_cities', as: 'update_cities'
  get 'welcome/show'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @countries = Country.all
    @cities = City.where("country_id = ?", Country.first.id)
  end

  def show
    @city = City.find_by("id = ?", params[:trip][:city_id])
  end

  def update_cities
    @cities = City.where("country_id = ?", params[:country_id])
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/_city.html.erb
<option value="<%= city.id %>"><%= city.name.titleize %></option>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dynboxes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<p>
  <%= form_for :trip, url: {action: "show"}, html: {method: "get"} do |f| %>
  <%= f.label "Pick a destination:" %>
  <%= f.select :country_id, options_for_select(@countries.collect { |country| [country.name.titleize, country.id] }, 1), {}, { id: 'countries_select' } %>
  <%= f.select :city_id, options_for_select(@cities.collect { |city| [city.name.titleize, city.id] }, 0), {}, { id: 'cities_select' } %>
  <%= f.submit "Go!" %>
  <% end %>
</p>

app/views/welcome/show.html.erb
<p>Congrats, you are going to <%= @city.name.titleize %>!</p>
<p><%= link_to 'Back', welcome_index_path %></p>